### ISSUE TITLE
Footer Text Invisibility in Light Theme: Adjusting Text Color for Cartesi Documentation

### ISSUE THREAD

**Issue by ATREAY** [cartesi/docs#148]
## Description:

In the Cartesi documentation, the footer text is not visible when the documentation theme is changed from dark to light. The issue can be observed [here](https://docs.cartesi.io/cartesi-machine/).

## Proposed Solution:

To address this issue, we propose changing the text color from white to black when the documentation theme is switched. This adjustment is necessary to ensure that the footer text remains visible regardless of the selected theme.

## Screenshot:

Dark Mode:
![image](https://github.com/cartesi/docs/assets/66585295/74c8c180-a90d-4507-9591-80db741f1bea)

Light Mode:
![light](https://github.com/cartesi/docs/assets/66585295/e9daa812-7504-4d1e-b548-8652d5defeca)

## Would you like to work on this issue?

- [x] Yes
- [ ] No

**Comment by masiedu4** [comment]
Hi @ATREAY , thanks for pointing this out! 🙌

**Comment by masiedu4** [comment]
Hi @ATREAY 

A PR resolving this issue has been merged!

https://github.com/cartesi/docs/pull/149

Thanks once again! 🙌
