### ISSUE TITLE
Missing doc about dapp.json

### ISSUE THREAD

**Issue by fabiooshiro** [cartesi/docs#38]
Hi guys!

Where I can find the doc about the file dapp.json?
https://github.com/Calindra/rollups-examples/blob/main/echo-rust/dapp.json

**Comment by nicocartesi** [comment]
Hi @fabiooshiro , The dapp.json file is a configuration file used in the previous build system to construct the file system for the DApp's Cartesi Machine. The files listed in the dapp.json file will be incorporated into the file system. In the new build system, such configurations are described in the Dockerfile.
