### ISSUE TITLE
Document the breaking change in the GraphQL regarding the output-validity-proof

### ISSUE THREAD

**Issue by nicocartesi** [cartesi/docs#55]
The Output Validity Proof feature has a number of components renamed as per https://github.com/cartesi/rollups/pull/122 The requirement is to update the docs accordingly.

**Comment by nicocartesi** [comment]
Thanks @claudioantonio , I have raised a PR for this - https://github.com/cartesi/docs/pull/56

**Comment by Payalpatelmalhotra** [comment]
@nicocartesi can this open issue be closed on the basis of this having been addressed in PR #56? FYI @claudioantonio

**Comment by claudioantonio** [comment]
@Payalpatelmalhotra @nicocartesi  this issue can be closed because PR #56 was alredy merge to `next` branch. 😉

**Comment by Payalpatelmalhotra** [comment]
@nicocartesi can you please close this?
