### ISSUE TITLE
Update "Deploying Dapps" section

### ISSUE THREAD

**Issue by claudioantonio** [cartesi/docs#65]
Context:
Cartesi will not be a validator anymore, with the exception for the honeypot. So it does not make sense to continue offering our cloud-based deployment and execution infrastructure.

Solution:
Dev will have to deploy their cartesi nodes. The README on `rollups-examples` repo provides instructions on how to run a Cartesi node for a Cartesi DApp. That said, we will need to update the "Deplying DApps" section on Cartesi docs.

@nicocartesi 👀

**Comment by nicocartesi** [comment]
@claudioantonio , can we close this as done?
