### ISSUE TITLE
Adapt docs to consider we will not have deployed examples running on Cartesi nodes

### ISSUE THREAD

**Issue by claudioantonio** [cartesi/docs#68]
**Context:**
the deployment landscape is different from that of couple months ago. Cartesi will not be a validator any longer, with the exception of the honeypot. There will be not a Cartesi validator node running for examples any longer. Another validator should do this instead. 
**Solution:**
Docs should not provide any links to online endpoints for `rollups-examples` and all contet where there are those links should be rewritten. For example, the section Quick Start where we can find instructions on how to interact with remotely deployed examples: https://docs.cartesi.io/cartesi-rollups/build-dapps/run-dapp/

@nicocartesi 👀

**Comment by nicocartesi** [comment]
Hi @claudioantonio , can we close this as done? Based on https://github.com/cartesi/docs/pull/81
