### ISSUE TITLE
Weird wording

### ISSUE THREAD

**Issue by MeerKatDev** [cartesi/docs#84]
From [here](https://docs.cartesi.io/cartesi-rollups/overview/), just before the summary of [this](https://docs.cartesi.io/cartesi-rollups/overview/#how-does-a-rollup-work) section.

> Naturally, this optimism comes paired up with financial incentives for honest behavior and guarantees that, unless the proposed false state is undisputed for a significant amount of time, it will never get accepted.

Sounds like the honest behavior won't get accepted?

**Comment by nicocartesi** [comment]
Thanks for the feedback @MeerKatDev , we've amended it https://github.com/cartesi/docs/pull/99
