### ISSUE TITLE
Adapt all content to remove Goerli references and use Sepolia instead

### ISSUE THREAD

**Issue by claudioantonio** [cartesi/docs#85]
**Context:** Cartesi Rollups v1 will not be deployed on Ethereum Goerli (Testnet). The Testnet deployment will be done only on Sepolia for Ethereum.
⚠️Optimism Goerli and Arbitrum Goerli will be supported.

@nicocartesi 👀

**Comment by Payalpatelmalhotra** [comment]
@nicocartesi since PR 86 was closed yesterday, can this issue be closed too? CC @claudioantonio
